const STORAGE_KEY="arEnnichiKitanProgressV1";
const questions=[
{destination:"D館へ向かえ",story:"最初の祭札は、高くそびえる建物の記憶に隠されている。",question:"D館は何階建て？",choices:["6階建て","7階建て","8階建て","9階建て"],answerIndex:2,letter:"ず",image:"",imageAlt:"D館の現地写真"},
{destination:"図書館の正面入口へ向かえ",story:"本の眠る場所の前に、次の記憶が残されている。",question:"図書館の正面入口を出て、すぐ目の前にあるものは？",choices:["駐車場","駐輪場","かみしんプラザ","A館"],answerIndex:1,letter:"い",image:"",imageAlt:"図書館正面入口の現地写真"},
{destination:"正門へ向かえ",story:"大学の名を示す看板を見つけ、刻まれた文字を確かめよ。",question:"看板に書かれている大阪経済大学の英語名は？",choices:["Osaka University of Economy","Osaka University of Economics","Osaka Economics University","Osaka University of Business"],answerIndex:1,letter:"こ",image:"",imageAlt:"正門の英語看板"},
{destination:"B館の入口へ向かえ",story:"最後の祭札は、建物の入口に残された名の記憶を待っている。",question:"入口の看板に書かれている建物名はどれ？",choices:["A館","B館","D館","図書館"],answerIndex:1,letter:"う",image:"",imageAlt:"B館入口の看板"}
];
const $=id=>document.getElementById(id);const screens={intro:$("introScreen"),question:$("questionScreen"),reward:$("rewardScreen"),final:$("finalScreen"),clear:$("clearScreen")};let state=load();
function fresh(){return{started:false,step:0,letters:[],cleared:false}}function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return v&&typeof v.step==="number"?v:fresh()}catch{return fresh()}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function show(name){Object.entries(screens).forEach(([k,e])=>e.hidden=k!==name);window.scrollTo({top:0,behavior:"smooth"})}
function progress(){$("progressText").textContent=`祭札 ${state.letters.length} / ${questions.length}`;$("progressDots").replaceChildren();questions.forEach((_,i)=>{const d=document.createElement("span");d.className="progress-dot"+(i<state.letters.length?" active":"");$("progressDots").appendChild(d)})}
function renderQuestion(){if(state.step>=questions.length)return renderFinal();const q=questions[state.step];$("stageLabel").textContent=`第${state.step+1}の記憶`;$("destination").textContent=q.destination;$("stageStory").textContent=q.story;$("questionText").textContent=q.question;$("feedback").textContent="";$("choices").replaceChildren();if(q.image){$("stageImage").src=q.image;$("stageImage").alt=q.imageAlt;$("photoFrame").hidden=false}else{$("photoFrame").hidden=true;$("stageImage").removeAttribute("src")}q.choices.forEach((c,i)=>{const b=document.createElement("button");b.type="button";b.className="choice-button";b.textContent=c;b.addEventListener("click",()=>check(i));$("choices").appendChild(b)});show("question");progress()}
function check(i){const q=questions[state.step];if(i!==q.answerIndex){$("feedback").textContent="違うようだ。現地をもう一度、よく確かめてみよう。";return}[...$("choices").querySelectorAll("button")].forEach(b=>b.disabled=true);if(!state.letters.includes(q.letter))state.letters.push(q.letter);save();$("earnedLetter").textContent=q.letter;$("rewardTitle").textContent=`祭札「${q.letter}」を取り戻した`;$("rewardMessage").textContent=state.step===questions.length-1?"四枚の祭札がそろった。最後の言葉を完成させよう。":"遠くで祭囃子が聞こえた気がした。次の場所へ向かおう。";$("nextButton").textContent=state.step===questions.length-1?"最後の言葉を完成させる":"次の記憶を探す";show("reward");progress()}
function next(){state.step++;save();state.step>=questions.length?renderFinal():renderQuestion()}
function renderFinal(){$("collectedLetters").replaceChildren();state.letters.forEach(l=>{const s=document.createElement("span");s.textContent=l;$("collectedLetters").appendChild(s)});$("finalFeedback").textContent="";$("finalAnswer").value="";show("final");progress()}
function finish(){const a=$("finalAnswer").value.normalize("NFKC").replace(/\s+/g,"");if(a!=="ずいこう"){$("finalFeedback").textContent="祭札の順番が違うようだ。集めた順に読んでみよう。";return}state.cleared=true;save();show("clear")}
function reset(){if(!confirm("進行状況を消して、最初から始めますか？"))return;state=fresh();localStorage.removeItem(STORAGE_KEY);progress();show("intro")}
$("startButton").addEventListener("click",()=>{state.started=true;save();renderQuestion()});$("nextButton").addEventListener("click",next);$("finalButton").addEventListener("click",finish);$("finalAnswer").addEventListener("keydown",e=>{if(e.key==="Enter")finish()});$("resetButton").addEventListener("click",reset);progress();if(state.cleared)show("clear");else if(state.started&&state.step>=questions.length)renderFinal();else if(state.started)renderQuestion();else show("intro");
